import './lazyer.scss'
export {default as LazyerSwitch} from './LazyerSwitch.vue'
export {default as LazyerButton} from './LazyerButton.vue'
export {default as LazyerTabs} from './LazyerTabs.vue'
export {default as LazyerTabsItem} from './LazyerTabsItem.vue'
export {default as LazyerDialog} from './LazyerDialog.vue'
export {default as LazyerDropdown} from './LazyerDropdown.vue'
export {default as LazyerMenuItem} from './LazyerMenuItem.vue'
export {openDialog as openDialog} from './openDialog'